# Generated by Django 5.1 on 2024-08-31 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_outlet', '0002_book_is_bestseller_alter_book_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='slug',
            field=models.SlugField(default='', max_length=100, unique=True),
        ),
    ]
